version: "3.5"

services:

  php:
    build:
      context: ~/docker/lamp-php56/php
    ports:
    - 127.0.0.1:80:80
    volumes:
    - ./htdocs:/var/www/html

  mariadb:
    image: mariadb:10.4
    ports:
    - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootroot
      MYSQL_DATABASE: testdb
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass
    volumes:
    - ./databases/mariadb:/var/lib/mysql
    - ./databases/conf.d:/etc/mysql/conf.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - 127.0.0.1:8080:80
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: rootroot
